name: Daily Investegate Scrape

on:
  schedule:
    # GitHub uses UTC. 06:30 UTC ≈ 5:30pm Sydney during AEDT.
    # If Sydney switches to AEST (UTC+10), change this to '30 07 * * *'.
    - cron: '30 06 * * *'
  workflow_dispatch:  # lets you run it manually

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml python-dateutil openai

      - name: Run scraper
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # remove if not using AI
        run: |
          python investegate_scraper.py \
            --pages 2 \
            --per_page 300 \
            --since_days 7 \
            --min_score 1 \
            --keywords_file keywords.txt \
            --use_ai true

      - name: Zip report folder
        run: |
          zip -r report.zip out/

      - name: Email report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Investegate RNS Digest – ${{ github.run_number }} ({{date}})"
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.FROM_EMAIL }}
          # Simple body; includes a link back to the run
          body: |
            Attached is today's Investegate RNS Digest (zipped).
            Run details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          content_type: text/plain
          attachments: report.zip


      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: investegate-out
          path: out/
